using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PedagangPulsa.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddUserDevicesAndPushChannel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This migration was originally a snapshot that recreated all tables.
            // Since tables already exist in the database, we use raw SQL with
            // exception handling to only create objects that don't exist yet.

            // Create enum types (skip if already exist)
            migrationBuilder.Sql(@"
                DO $$ BEGIN CREATE TYPE admin_role AS ENUM ('superadmin', 'admin', 'finance', 'staff'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE attempt_status AS ENUM ('pending', 'processing', 'success', 'failed', 'timeout'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE balance_tx_type AS ENUM ('topup', 'purchase_hold', 'purchase_debit', 'purchase_release', 'transfer_out', 'transfer_in', 'refund', 'adjustment'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE markup_type AS ENUM ('percentage', 'fixed'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE notification_channel AS ENUM ('email', 'sms', 'whatsapp', 'push'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE referral_bonus_status AS ENUM ('pending', 'paid', 'cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE topup_status AS ENUM ('pending', 'approved', 'rejected'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE transaction_status AS ENUM ('pending', 'processing', 'success', 'failed', 'refunded', 'cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
                DO $$ BEGIN CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended'); EXCEPTION WHEN duplicate_object THEN null; END $$;
            ");

            // Create tables (skip if already exist)
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    CREATE TABLE ""AdminUsers"" (
                        ""Id"" uuid NOT NULL,
                        ""Username"" character varying(50) NOT NULL,
                        ""Email"" character varying(100) NOT NULL,
                        ""PasswordHash"" character varying(255) NOT NULL,
                        ""Role"" text NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""LastLoginAt"" timestamp with time zone,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_AdminUsers"" PRIMARY KEY (""Id"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""AuditLogs"" (
                        ""Id"" bigint NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""ActorType"" character varying(10) NOT NULL,
                        ""ActorId"" uuid NOT NULL,
                        ""Action"" character varying(100) NOT NULL,
                        ""Entity"" character varying(50),
                        ""EntityId"" text,
                        ""OldValue"" text,
                        ""NewValue"" text,
                        ""IpAddress"" character varying(45),
                        ""UserAgent"" text,
                        CONSTRAINT ""PK_AuditLogs"" PRIMARY KEY (""Id"", ""CreatedAt"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""BankAccounts"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""BankName"" character varying(50) NOT NULL,
                        ""AccountNumber"" character varying(30) NOT NULL,
                        ""AccountName"" character varying(100) NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_BankAccounts"" PRIMARY KEY (""Id"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""NotificationTemplates"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""Code"" character varying(50) NOT NULL,
                        ""Channel"" text NOT NULL,
                        ""Subject"" character varying(200),
                        ""Body"" text NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        CONSTRAINT ""PK_NotificationTemplates"" PRIMARY KEY (""Id"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""ProductCategories"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""Name"" character varying(100) NOT NULL,
                        ""Code"" character varying(20) NOT NULL,
                        ""IconUrl"" text,
                        ""SortOrder"" smallint NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        CONSTRAINT ""PK_ProductCategories"" PRIMARY KEY (""Id"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""Suppliers"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""Name"" character varying(100) NOT NULL,
                        ""Code"" character varying(20) NOT NULL,
                        ""ApiBaseUrl"" text,
                        ""MemberId"" text,
                        ""Pin"" text,
                        ""Password"" text,
                        ""TimeoutSeconds"" smallint NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_Suppliers"" PRIMARY KEY (""Id"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""UserLevels"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""Name"" character varying(50) NOT NULL,
                        ""Description"" text,
                        ""MarkupType"" text NOT NULL,
                        ""MarkupValue"" numeric(10,4) NOT NULL,
                        ""CanTransfer"" boolean NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_UserLevels"" PRIMARY KEY (""Id"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""Products"" (
                        ""Id"" uuid NOT NULL,
                        ""CategoryId"" integer NOT NULL,
                        ""Name"" character varying(150) NOT NULL,
                        ""Code"" character varying(50) NOT NULL,
                        ""Denomination"" numeric(15,2),
                        ""Operator"" character varying(50),
                        ""Description"" text,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_Products"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_Products_ProductCategories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""ProductCategories""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""SupplierBalances"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""SupplierId"" integer NOT NULL,
                        ""ActiveBalance"" numeric(15,2) NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_SupplierBalances"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_SupplierBalances_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""UserLevelConfigs"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""LevelId"" integer NOT NULL,
                        ""ConfigKey"" character varying(100) NOT NULL,
                        ""ConfigValue"" text NOT NULL,
                        ""Description"" text,
                        CONSTRAINT ""PK_UserLevelConfigs"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_UserLevelConfigs_UserLevels_LevelId"" FOREIGN KEY (""LevelId"") REFERENCES ""UserLevels""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""Users"" (
                        ""Id"" uuid NOT NULL,
                        ""Username"" character varying(50) NOT NULL,
                        ""Email"" character varying(100),
                        ""FullName"" text,
                        ""Phone"" character varying(20),
                        ""PasswordHash"" character varying(255),
                        ""PinHash"" character varying(255) NOT NULL,
                        ""PinFailedAttempts"" smallint NOT NULL,
                        ""PinLockedAt"" timestamp with time zone,
                        ""LevelId"" integer NOT NULL,
                        ""CanTransferOverride"" boolean,
                        ""ReferralCode"" character varying(20) NOT NULL,
                        ""Status"" text NOT NULL,
                        ""EmailVerifiedAt"" timestamp with time zone,
                        ""PhoneVerifiedAt"" timestamp with time zone,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_Users_UserLevels_LevelId"" FOREIGN KEY (""LevelId"") REFERENCES ""UserLevels""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""ProductLevelPrices"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""ProductId"" uuid NOT NULL,
                        ""LevelId"" integer NOT NULL,
                        ""Margin"" numeric(15,2) NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_ProductLevelPrices"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_ProductLevelPrices_Products_ProductId"" FOREIGN KEY (""ProductId"") REFERENCES ""Products""(""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_ProductLevelPrices_UserLevels_LevelId"" FOREIGN KEY (""LevelId"") REFERENCES ""UserLevels""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""SupplierProducts"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""ProductId"" uuid NOT NULL,
                        ""SupplierId"" integer NOT NULL,
                        ""SupplierProductCode"" character varying(100) NOT NULL,
                        ""SupplierProductName"" character varying(150),
                        ""CostPrice"" numeric(15,2) NOT NULL,
                        ""Seq"" smallint NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_SupplierProducts"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_SupplierProducts_Products_ProductId"" FOREIGN KEY (""ProductId"") REFERENCES ""Products""(""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_SupplierProducts_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""SupplierBalanceLedgers"" (
                        ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                        ""SupplierId"" integer NOT NULL,
                        ""Type"" text NOT NULL,
                        ""Amount"" numeric(15,2) NOT NULL,
                        ""BalanceBefore"" numeric(15,2) NOT NULL,
                        ""BalanceAfter"" numeric(15,2) NOT NULL,
                        ""Description"" text,
                        ""AdminNote"" text,
                        ""PerformedBy"" text,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""SupplierBalanceId"" integer,
                        CONSTRAINT ""PK_SupplierBalanceLedgers"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_SupplierBalanceLedgers_SupplierBalances_SupplierBalanceId"" FOREIGN KEY (""SupplierBalanceId"") REFERENCES ""SupplierBalances""(""Id""),
                        CONSTRAINT ""FK_SupplierBalanceLedgers_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""BalanceLedgers"" (
                        ""Id"" bigint NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""Type"" text NOT NULL,
                        ""Amount"" numeric(15,2) NOT NULL,
                        ""ActiveBefore"" numeric(15,2) NOT NULL,
                        ""ActiveAfter"" numeric(15,2) NOT NULL,
                        ""HeldBefore"" numeric(15,2) NOT NULL,
                        ""HeldAfter"" numeric(15,2) NOT NULL,
                        ""RefType"" text,
                        ""RefId"" uuid,
                        ""Notes"" text,
                        ""CreatedBy"" uuid,
                        CONSTRAINT ""PK_BalanceLedgers"" PRIMARY KEY (""Id"", ""CreatedAt""),
                        CONSTRAINT ""FK_BalanceLedgers_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""IdempotencyKeys"" (
                        ""Key"" character varying(200) NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""TransactionId"" uuid,
                        ""ResponseCache"" text,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""ExpiresAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_IdempotencyKeys"" PRIMARY KEY (""UserId"", ""Key""),
                        CONSTRAINT ""FK_IdempotencyKeys_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""NotificationLogs"" (
                        ""Id"" bigint NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""Channel"" text NOT NULL,
                        ""TemplateCode"" character varying(50),
                        ""Recipient"" character varying(100) NOT NULL,
                        ""Subject"" character varying(200),
                        ""Body"" text,
                        ""Status"" character varying(20) NOT NULL,
                        ""RefType"" character varying(50),
                        ""RefId"" uuid,
                        ""SentAt"" timestamp with time zone,
                        ""RetryCount"" smallint NOT NULL,
                        ""ErrorMessage"" text,
                        CONSTRAINT ""PK_NotificationLogs"" PRIMARY KEY (""Id"", ""CreatedAt""),
                        CONSTRAINT ""FK_NotificationLogs_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""PeerTransfers"" (
                        ""Id"" uuid NOT NULL,
                        ""FromUserId"" uuid NOT NULL,
                        ""ToUserId"" uuid NOT NULL,
                        ""Amount"" numeric(15,2) NOT NULL,
                        ""Notes"" text,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_PeerTransfers"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_PeerTransfers_Users_FromUserId"" FOREIGN KEY (""FromUserId"") REFERENCES ""Users""(""Id"") ON DELETE RESTRICT,
                        CONSTRAINT ""FK_PeerTransfers_Users_ToUserId"" FOREIGN KEY (""ToUserId"") REFERENCES ""Users""(""Id"") ON DELETE RESTRICT
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""PinResetTokens"" (
                        ""Id"" uuid NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""TokenHash"" character varying(255) NOT NULL,
                        ""Channel"" character varying(10) NOT NULL,
                        ""ExpiresAt"" timestamp with time zone NOT NULL,
                        ""UsedAt"" timestamp with time zone,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_PinResetTokens"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_PinResetTokens_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""ReferralLogs"" (
                        ""Id"" uuid NOT NULL,
                        ""ReferrerId"" uuid NOT NULL,
                        ""RefereeId"" uuid NOT NULL,
                        ""BonusAmount"" numeric(15,2),
                        ""BonusStatus"" text NOT NULL,
                        ""Notes"" text,
                        ""PaidBy"" uuid,
                        ""PaidAt"" timestamp with time zone,
                        ""CancelledBy"" uuid,
                        ""CancelledAt"" timestamp with time zone,
                        ""CancellationReason"" text,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_ReferralLogs"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_ReferralLogs_Users_RefereeId"" FOREIGN KEY (""RefereeId"") REFERENCES ""Users""(""Id"") ON DELETE RESTRICT,
                        CONSTRAINT ""FK_ReferralLogs_Users_ReferrerId"" FOREIGN KEY (""ReferrerId"") REFERENCES ""Users""(""Id"") ON DELETE RESTRICT
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""RefreshTokens"" (
                        ""Id"" uuid NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""Token"" character varying(500) NOT NULL,
                        ""ExpiresAt"" timestamp with time zone NOT NULL,
                        ""IsRevoked"" boolean NOT NULL,
                        ""RevokedAt"" timestamp with time zone,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_RefreshTokens"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_RefreshTokens_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""TopupRequests"" (
                        ""Id"" uuid NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""BankAccountId"" integer,
                        ""Amount"" numeric(15,2) NOT NULL,
                        ""UniqueCode"" integer NOT NULL,
                        ""TransferProofUrl"" text,
                        ""Status"" text NOT NULL,
                        ""RejectReason"" text,
                        ""Notes"" text,
                        ""ApprovedBy"" uuid,
                        ""ApprovedAt"" timestamp with time zone,
                        ""RejectedBy"" uuid,
                        ""RejectedAt"" timestamp with time zone,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_TopupRequests"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_TopupRequests_BankAccounts_BankAccountId"" FOREIGN KEY (""BankAccountId"") REFERENCES ""BankAccounts""(""Id""),
                        CONSTRAINT ""FK_TopupRequests_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""Transactions"" (
                        ""Id"" uuid NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""ReferenceId"" character varying(100) NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""ProductId"" uuid NOT NULL,
                        ""Destination"" character varying(100) NOT NULL,
                        ""SellPrice"" numeric(15,2) NOT NULL,
                        ""CostPrice"" numeric(15,2),
                        ""Status"" text NOT NULL,
                        ""CurrentSeq"" smallint NOT NULL,
                        ""PinVerifiedAt"" timestamp with time zone NOT NULL,
                        ""Sn"" text,
                        ""ErrorMessage"" text,
                        ""CompletedAt"" timestamp with time zone,
                        ""SerialNumber"" text,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        ""SupplierId"" integer,
                        ""SupplierTrxId"" text,
                        CONSTRAINT ""PK_Transactions"" PRIMARY KEY (""Id"", ""CreatedAt""),
                        CONSTRAINT ""AK_Transactions_Id"" UNIQUE (""Id""),
                        CONSTRAINT ""FK_Transactions_Products_ProductId"" FOREIGN KEY (""ProductId"") REFERENCES ""Products""(""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_Transactions_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers""(""Id""),
                        CONSTRAINT ""FK_Transactions_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""UserBalances"" (
                        ""UserId"" uuid NOT NULL,
                        ""ActiveBalance"" numeric(15,2) NOT NULL,
                        ""HeldBalance"" numeric(15,2) NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_UserBalances"" PRIMARY KEY (""UserId""),
                        CONSTRAINT ""FK_UserBalances_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""UserDevices"" (
                        ""Id"" uuid NOT NULL,
                        ""UserId"" uuid NOT NULL,
                        ""FcmToken"" character varying(500) NOT NULL,
                        ""DeviceName"" character varying(100),
                        ""Platform"" character varying(20),
                        ""AppVersion"" character varying(20),
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""LastActiveAt"" timestamp with time zone,
                        ""IsActive"" boolean NOT NULL,
                        CONSTRAINT ""PK_UserDevices"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_UserDevices_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""TransactionAttempts"" (
                        ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                        ""TransactionId"" uuid NOT NULL,
                        ""SupplierId"" integer NOT NULL,
                        ""SupplierProductId"" integer NOT NULL,
                        ""Seq"" smallint NOT NULL,
                        ""Status"" text NOT NULL,
                        ""SupplierRefId"" character varying(100),
                        ""SupplierTrxId"" character varying(100),
                        ""RequestPayload"" text,
                        ""ResponsePayload"" text,
                        ""ErrorCode"" character varying(50),
                        ""ErrorMessage"" text,
                        ""AttemptedAt"" timestamp with time zone NOT NULL,
                        ""CompletedAt"" timestamp with time zone,
                        CONSTRAINT ""PK_TransactionAttempts"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_TransactionAttempts_SupplierProducts_SupplierProductId"" FOREIGN KEY (""SupplierProductId"") REFERENCES ""SupplierProducts""(""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_TransactionAttempts_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers""(""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_TransactionAttempts_Transactions_TransactionId"" FOREIGN KEY (""TransactionId"") REFERENCES ""Transactions""(""Id"") ON DELETE CASCADE
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;

                DO $$ BEGIN
                    CREATE TABLE ""SupplierCallbacks"" (
                        ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                        ""SupplierId"" integer NOT NULL,
                        ""RawHeaders"" text,
                        ""RawPayload"" text NOT NULL,
                        ""IpAddress"" character varying(45),
                        ""HmacValid"" boolean NOT NULL,
                        ""AttemptId"" bigint,
                        ""IsProcessed"" boolean NOT NULL,
                        ""ProcessedAt"" timestamp with time zone,
                        ""ErrorMessage"" text,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_SupplierCallbacks"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_SupplierCallbacks_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers""(""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_SupplierCallbacks_TransactionAttempts_AttemptId"" FOREIGN KEY (""AttemptId"") REFERENCES ""TransactionAttempts""(""Id"")
                    );
                EXCEPTION WHEN duplicate_table THEN null; END $$;
            ");

            // Create indexes (skip if already exist)
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AdminUsers_Email"" ON ""AdminUsers"" (""Email"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AdminUsers_Username"" ON ""AdminUsers"" (""Username"");
                CREATE INDEX IF NOT EXISTS ""IX_AuditLogs_ActorId_CreatedAt"" ON ""AuditLogs"" (""ActorId"", ""CreatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_AuditLogs_Entity_EntityId"" ON ""AuditLogs"" (""Entity"", ""EntityId"");
                CREATE INDEX IF NOT EXISTS ""IX_BalanceLedgers_RefType_RefId"" ON ""BalanceLedgers"" (""RefType"", ""RefId"");
                CREATE INDEX IF NOT EXISTS ""IX_BalanceLedgers_UserId_CreatedAt"" ON ""BalanceLedgers"" (""UserId"", ""CreatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_IdempotencyKeys_ExpiresAt"" ON ""IdempotencyKeys"" (""ExpiresAt"");
                CREATE INDEX IF NOT EXISTS ""IX_NotificationLogs_Status_CreatedAt"" ON ""NotificationLogs"" (""Status"", ""CreatedAt"") WHERE ""NotificationLogs"".""Status"" = 'pending';
                CREATE INDEX IF NOT EXISTS ""IX_NotificationLogs_UserId_CreatedAt"" ON ""NotificationLogs"" (""UserId"", ""CreatedAt"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_NotificationTemplates_Code_Channel"" ON ""NotificationTemplates"" (""Code"", ""Channel"");
                CREATE INDEX IF NOT EXISTS ""IX_PeerTransfers_FromUserId_CreatedAt"" ON ""PeerTransfers"" (""FromUserId"", ""CreatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_PeerTransfers_ToUserId_CreatedAt"" ON ""PeerTransfers"" (""ToUserId"", ""CreatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_PinResetTokens_UserId_ExpiresAt"" ON ""PinResetTokens"" (""UserId"", ""ExpiresAt"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ProductCategories_Code"" ON ""ProductCategories"" (""Code"");
                CREATE INDEX IF NOT EXISTS ""IX_ProductLevelPrices_LevelId"" ON ""ProductLevelPrices"" (""LevelId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ProductLevelPrices_ProductId_LevelId"" ON ""ProductLevelPrices"" (""ProductId"", ""LevelId"");
                CREATE INDEX IF NOT EXISTS ""IX_ProductLevelPrices_ProductId_LevelId_IsActive"" ON ""ProductLevelPrices"" (""ProductId"", ""LevelId"", ""IsActive"");
                CREATE INDEX IF NOT EXISTS ""IX_Products_CategoryId_IsActive"" ON ""Products"" (""CategoryId"", ""IsActive"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Products_Code"" ON ""Products"" (""Code"");
                CREATE INDEX IF NOT EXISTS ""IX_Products_Operator"" ON ""Products"" (""Operator"");
                CREATE INDEX IF NOT EXISTS ""IX_ReferralLogs_BonusStatus_CreatedAt"" ON ""ReferralLogs"" (""BonusStatus"", ""CreatedAt"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ReferralLogs_RefereeId"" ON ""ReferralLogs"" (""RefereeId"");
                CREATE INDEX IF NOT EXISTS ""IX_ReferralLogs_ReferrerId_BonusStatus"" ON ""ReferralLogs"" (""ReferrerId"", ""BonusStatus"");
                CREATE INDEX IF NOT EXISTS ""IX_RefreshTokens_Token"" ON ""RefreshTokens"" (""Token"");
                CREATE INDEX IF NOT EXISTS ""IX_RefreshTokens_UserId_IsRevoked_ExpiresAt"" ON ""RefreshTokens"" (""UserId"", ""IsRevoked"", ""ExpiresAt"");
                CREATE INDEX IF NOT EXISTS ""IX_SupplierBalanceLedgers_SupplierBalanceId"" ON ""SupplierBalanceLedgers"" (""SupplierBalanceId"");
                CREATE INDEX IF NOT EXISTS ""IX_SupplierBalanceLedgers_SupplierId_CreatedAt"" ON ""SupplierBalanceLedgers"" (""SupplierId"", ""CreatedAt"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_SupplierBalances_SupplierId"" ON ""SupplierBalances"" (""SupplierId"");
                CREATE INDEX IF NOT EXISTS ""IX_SupplierCallbacks_AttemptId"" ON ""SupplierCallbacks"" (""AttemptId"");
                CREATE INDEX IF NOT EXISTS ""IX_SupplierCallbacks_CreatedAt_IsProcessed"" ON ""SupplierCallbacks"" (""CreatedAt"", ""IsProcessed"") WHERE ""SupplierCallbacks"".""IsProcessed"" = false;
                CREATE INDEX IF NOT EXISTS ""IX_SupplierCallbacks_SupplierId"" ON ""SupplierCallbacks"" (""SupplierId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_SupplierProducts_ProductId_Seq"" ON ""SupplierProducts"" (""ProductId"", ""Seq"");
                CREATE INDEX IF NOT EXISTS ""IX_SupplierProducts_ProductId_Seq_IsActive"" ON ""SupplierProducts"" (""ProductId"", ""Seq"", ""IsActive"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_SupplierProducts_ProductId_SupplierId"" ON ""SupplierProducts"" (""ProductId"", ""SupplierId"");
                CREATE INDEX IF NOT EXISTS ""IX_SupplierProducts_SupplierId"" ON ""SupplierProducts"" (""SupplierId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Suppliers_Code"" ON ""Suppliers"" (""Code"");
                CREATE INDEX IF NOT EXISTS ""IX_TopupRequests_BankAccountId"" ON ""TopupRequests"" (""BankAccountId"");
                CREATE INDEX IF NOT EXISTS ""IX_TopupRequests_Status_CreatedAt"" ON ""TopupRequests"" (""Status"", ""CreatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_TopupRequests_UserId_CreatedAt"" ON ""TopupRequests"" (""UserId"", ""CreatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_TransactionAttempts_Status_AttemptedAt"" ON ""TransactionAttempts"" (""Status"", ""AttemptedAt"") WHERE ""TransactionAttempts"".""Status"" IN ('pending', 'processing');
                CREATE INDEX IF NOT EXISTS ""IX_TransactionAttempts_SupplierId"" ON ""TransactionAttempts"" (""SupplierId"");
                CREATE INDEX IF NOT EXISTS ""IX_TransactionAttempts_SupplierProductId"" ON ""TransactionAttempts"" (""SupplierProductId"");
                CREATE INDEX IF NOT EXISTS ""IX_TransactionAttempts_SupplierRefId"" ON ""TransactionAttempts"" (""SupplierRefId"") WHERE ""TransactionAttempts"".""SupplierRefId"" IS NOT NULL;
                CREATE INDEX IF NOT EXISTS ""IX_TransactionAttempts_TransactionId"" ON ""TransactionAttempts"" (""TransactionId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_TransactionAttempts_TransactionId_Seq"" ON ""TransactionAttempts"" (""TransactionId"", ""Seq"");
                CREATE INDEX IF NOT EXISTS ""IX_Transactions_ProductId"" ON ""Transactions"" (""ProductId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Transactions_ReferenceId"" ON ""Transactions"" (""ReferenceId"");
                CREATE INDEX IF NOT EXISTS ""IX_Transactions_Status_CreatedAt"" ON ""Transactions"" (""Status"", ""CreatedAt"") WHERE ""Transactions"".""Status"" IN ('pending', 'processing');
                CREATE INDEX IF NOT EXISTS ""IX_Transactions_SupplierId"" ON ""Transactions"" (""SupplierId"");
                CREATE INDEX IF NOT EXISTS ""IX_Transactions_UserId_CreatedAt"" ON ""Transactions"" (""UserId"", ""CreatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_UserDevices_FcmToken"" ON ""UserDevices"" (""FcmToken"");
                CREATE INDEX IF NOT EXISTS ""IX_UserDevices_IsActive"" ON ""UserDevices"" (""IsActive"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserDevices_UserId_FcmToken"" ON ""UserDevices"" (""UserId"", ""FcmToken"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserLevelConfigs_LevelId_ConfigKey"" ON ""UserLevelConfigs"" (""LevelId"", ""ConfigKey"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserLevels_Name"" ON ""UserLevels"" (""Name"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Email"" ON ""Users"" (""Email"");
                CREATE INDEX IF NOT EXISTS ""IX_Users_LevelId"" ON ""Users"" (""LevelId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Phone"" ON ""Users"" (""Phone"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_ReferralCode"" ON ""Users"" (""ReferralCode"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Username"" ON ""Users"" (""Username"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AdminUsers");

            migrationBuilder.DropTable(
                name: "AuditLogs");

            migrationBuilder.DropTable(
                name: "BalanceLedgers");

            migrationBuilder.DropTable(
                name: "IdempotencyKeys");

            migrationBuilder.DropTable(
                name: "NotificationLogs");

            migrationBuilder.DropTable(
                name: "NotificationTemplates");

            migrationBuilder.DropTable(
                name: "PeerTransfers");

            migrationBuilder.DropTable(
                name: "PinResetTokens");

            migrationBuilder.DropTable(
                name: "ProductLevelPrices");

            migrationBuilder.DropTable(
                name: "ReferralLogs");

            migrationBuilder.DropTable(
                name: "RefreshTokens");

            migrationBuilder.DropTable(
                name: "SupplierBalanceLedgers");

            migrationBuilder.DropTable(
                name: "SupplierCallbacks");

            migrationBuilder.DropTable(
                name: "TopupRequests");

            migrationBuilder.DropTable(
                name: "UserBalances");

            migrationBuilder.DropTable(
                name: "UserDevices");

            migrationBuilder.DropTable(
                name: "UserLevelConfigs");

            migrationBuilder.DropTable(
                name: "SupplierBalances");

            migrationBuilder.DropTable(
                name: "TransactionAttempts");

            migrationBuilder.DropTable(
                name: "BankAccounts");

            migrationBuilder.DropTable(
                name: "SupplierProducts");

            migrationBuilder.DropTable(
                name: "Transactions");

            migrationBuilder.DropTable(
                name: "Products");

            migrationBuilder.DropTable(
                name: "Suppliers");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "ProductCategories");

            migrationBuilder.DropTable(
                name: "UserLevels");
        }
    }
}
